# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Events"
  url = "#events"
  weight = 20

[[main]]
  name = "Sponsors"
  url = "sponsors"
  weight = 30

[[main]]
  name = "Organisers"
  url = "#"
  hasChildren = true
  weight = 40

[[main]]
  parent = "Organisers"
  name = "Sarah"
  url = "#sarah"
  weight = 10

[[main]]
  parent = "Organisers"
  name = "Gregor"
  url = "#gregor"
  weight = 20

[[main]]
  name = "Newsletter"
  url = "#newsletter"
  weight = 50

[[main]]
  name = "Code of Conduct"
  url = "conduct"
  weight = 60


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
